<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.github.soprasteria</groupId>
  <artifactId>wsq4j</artifactId>
  <name>wsq4j</name>
  <version>1.0</version>
  <description>
    Java library for decoding, encoding WSQ images.
  </description>
  <url>https://github.com/soprasteria/wsq4j</url>
  <inceptionYear>2025</inceptionYear>

  <organization>
    <name>Sopra Steria Group</name>
    <url>https://www.soprasteria.com</url>
  </organization>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <properties>
    <java.version>8</java.version>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <mavenCentralAutoReleaseAfterClose>false</mavenCentralAutoReleaseAfterClose>
    <lombok.version>1.18.48</lombok.version>
    <assertj.version>3.27.7</assertj.version>
    <junit.version>6.1.3</junit.version>
    <mockito-core.version>5.24.0</mockito-core.version>
    <wsq-sf-id>${env.WSQ_SF_ID}</wsq-sf-id>
    <wsq-comment>wsq4j ${project.version}</wsq-comment>
  </properties>

  <developers>
    <developer>
      <id>mchesneau</id>
      <name>Manuel CHESNEAU</name>
      <roles>
        <role>architect</role>
        <role>developer</role>
      </roles>
    </developer>
  </developers>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.6.3</version>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>3.8</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!--   Compiler   -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.16.0</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <!--
            Tests, liés à jacoco
      -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.6.0</version>
        <configuration>
          <argLine>@{argLine} -Dfile.encoding=UTF-8</argLine>
          <useModulePath>false</useModulePath>
        </configuration>
      </plugin>
      <!--
              Couverture du code par les tests
              - résultat dans target/site/jacoco/index.html
      -->
      <plugin>
        <artifactId>jacoco-maven-plugin</artifactId>
        <groupId>org.jacoco</groupId>
        <version>0.8.15</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
            <id>coverage-initialize</id>
          </execution>
        </executions>
      </plugin>
      <!--
             Formatage du code
      -->
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>3.10.2</version>
        <configuration>
          <formats>
            <format>
              <endWithNewline/>
              <includes>
                <include>.gitattributes</include>
                <include>.gitignore</include>
                <include>**/*.xml</include>
                <include>**/*.md</include>
              </includes>
              <indent>
                <spaces>true</spaces>
                <spacesPerTab>2</spacesPerTab>
              </indent>
              <trimTrailingWhitespace/>
            </format>
          </formats>
          <java>
            <licenseHeader>
              <file>${project.basedir}/license-header.txt</file>
            </licenseHeader>
            <googleJavaFormat>
              <formatJavadoc>false</formatJavadoc>
              <reflowLongStrings>true</reflowLongStrings>
              <style>GOOGLE</style>
              <version>1.36.1</version>
            </googleJavaFormat>
          </java>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>apply</goal>
            </goals>
            <id>spotless-apply</id>
            <phase>validate</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>${lombok.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.20</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.6.4</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>${assertj.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <scope>test</scope>
      <version>${mockito-core.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio-pnm</artifactId>
      <version>3.15.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.22.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <scm>
    <connection>scm:git:https://github.com/soprasteria/wsq4j.git</connection>
    <developerConnection>scm:git:https://github.com/soprasteria/wsq4j.git</developerConnection>
    <url>https://github.com/soprasteria/wsq4j</url>
    <tag>HEAD</tag>
  </scm>

  <distributionManagement>
    <snapshotRepository>
      <id>ossrh</id>
      <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
    </snapshotRepository>
    <repository>
      <id>ossrh</id>
      <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
  </distributionManagement>
  <repositories>
    <repository>
      <id>gitlab-maven</id>
      <url>https://innersource.soprasteria.com/api/v4/projects/555198/packages/maven</url>
    </repository>
  </repositories>

  <profiles>
    <profile>
      <id>display-dependency-updates</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>versions-maven-plugin</artifactId>
            <version>2.22.0</version>
            <configuration>
              <ruleSet>
                <ignoreVersions>
                  <ignoreVersion>
                    <type>regex</type>
                    <version>(?i).*Alpha(?:-?\d+)?</version>
                  </ignoreVersion>
                  <ignoreVersion>
                    <type>regex</type>
                    <version>(?i).*a(?:-?\d+)?</version>
                  </ignoreVersion>
                  <ignoreVersion>
                    <type>regex</type>
                    <version>(?i).*Beta(?:-?\d+)?</version>
                  </ignoreVersion>
                  <ignoreVersion>
                    <type>regex</type>
                    <version>(?i).*-B(?:-?\d+)?</version>
                  </ignoreVersion>
                  <ignoreVersion>
                    <type>regex</type>
                    <version>(?i).*RC(?:-?\d+)?</version>
                  </ignoreVersion>
                  <ignoreVersion>
                    <type>regex</type>
                    <version>(?i).*CR(?:-?\d+)?</version>
                  </ignoreVersion>
                  <ignoreVersion>
                    <type>regex</type>
                    <version>(?i).*M(?:-?\d+)?</version>
                  </ignoreVersion>
                </ignoreVersions>
              </ruleSet>
            </configuration>
            <executions>
              <execution>
                <phase>compile</phase>
                <goals>
                  <goal>display-dependency-updates</goal>
                  <goal>display-plugin-updates</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>publish-central</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <version>3.12.0</version>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <version>3.4.0</version>
            <executions>
              <execution>
                <id>attach-sources</id>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>3.2.8</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <!-- deploy jar in maven central or stagging only : mvn clean deploy
               if autoReleaseAfterClose == true then release in maven central;
               if autoReleaseAfterClose == false then release in stagging only not maven central
          -->
          <plugin>
            <groupId>org.sonatype.central</groupId>
            <artifactId>central-publishing-maven-plugin</artifactId>
            <version>0.11.0</version>
            <extensions>true</extensions>
            <configuration>
              <publishingServerId>ossrh</publishingServerId>
              <autoPublish>${mavenCentralAutoReleaseAfterClose}</autoPublish>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
